
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:513940282548:android:82a586d3b7b0b7f6f48be1",
        firebase_cli_token: ENV["FIREBASE_CLI"]
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        upload_timeout: "1800",
        testers: "osama7emara@gmail.com",
        release_notes: "new update"
      )
  end
end
